# Generated by Django 4.0.3 on 2022-04-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscription'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(
                fields=('following', 'user'),
                name='subscription_unique'
            ),
        ),
    ]
